### ISSUE TITLE
Needs more game

### ISSUE THREAD

**Issue by zacnomore** [LithiumBeach/Prototypes#1]
Where's that fed at

**Comment by LithiumBeach** [comment]
fed's dead

**Comment by LithiumBeach** [comment]
That next commit is gonna be Meaty. Unity was a terrible idea its gone. Instead of starting with a presentation layer I've started with like. Data structures and type flexibility. Worm like flexibility in (not) differentiating assets from financial entities in any meaningful way, and with practically no adherence to polymorphism. So I started a new SFML C++ project lmao jk its in python now eat a bag of dicks it's gonna be networked too get out of my swamp.

**Comment by zacnomore** [comment]
Needs more swamp

**Comment by LithiumBeach** [comment]
here ya go fucknuts

**Comment by LithiumBeach** [comment]
https://github.com/LithiumBeach/CentralBanker

**Comment by zacnomore** [comment]
Looks like it's private... :(
